baseURL = "https://edit-mr.github.io/notes"
languageCode = "en"
title = "毛哥EM的筆記 EM's Notes"
theme = "aether"
googleAnalytics = "G-9R5PZG2VQG"

[params]
  brand = "EM's Notes"
  description = "My notes for everyting"
  # bgimg = "Path, within the 'assets' folder, of the image used for the page background - optional"
  headshotimg = "assets/img/me.jpg"
  headshotalt = "This is me"
  rssinmenu = false
  github = "https://github.com/Edit-Mr"
  instagram = "https://www.instagram.com/elvisdragonmao/"
  youtube = "https://www.youtube.com/channel/UCiXuSx3IuiYI87dHOhVxC6A"

[markup]
  [markup.highlight]
    style = "igor"
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files